# Generated by Django 4.0.5 on 2022-06-08 00:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=200)),
                ('drink_ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('garnishes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('recipie', models.CharField(max_length=2000)),
                ('glass', models.CharField(max_length=200)),
                ('tools', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('drink_pk', models.CharField(max_length=300)),
                ('drink_fk', models.CharField(max_length=300)),
                ('drink_string', models.CharField(max_length=200)),
                ('drink_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
            ],
            options={
                'ordering': ['drink_name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=200)),
                ('ingredient_pk', models.CharField(max_length=300)),
                ('ingredient_fk', models.CharField(max_length=300)),
                ('ingredient_string', models.CharField(max_length=200)),
                ('ingredient_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
            ],
            options={
                'ordering': ['ingredient'],
            },
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.CharField(max_length=300)),
                ('list_descriptions', models.CharField(max_length=300)),
                ('list_pk', models.CharField(max_length=300)),
                ('list_fk', models.CharField(max_length=300)),
                ('list_need_array', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('list_need_string', models.CharField(max_length=200)),
                ('drink_in_list', models.ManyToManyField(to='drinks.drinks')),
            ],
        ),
    ]
